services:
  postgres:
    image: postgres:latest
    container_name: savings_DB
    environment:
      POSTGRES_DB: savings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5332:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db
volumes:
  postgres-data:
networks:
  db:
    driver: bridge

